\c museum_dev;

INSERT INTO dinosaurs (dinosaur_id, name, pronunciation, meaning_of_name, diet, length_in_meters, period, mya, description, is_favorite) VALUES
('YLtkN9R37', 'Allosaurus', 'AL-oh-sore-us', 'other lizard', 'carnivorous', 12, 'Late Jurassic', '156, 144', 'Allosaurus was an apex predator in the Late Jurassic in North America.', true),
('GGvO1X9Zeh', 'Apatosaurus', 'ah-PAT-oh-sore-us', 'deceptive lizard', 'herbivorous', 21, 'Late Jurassic', '154, 145', 'Named the ''deceptive lizard'' because its skull was confused with those of other sauropods until 1909.', false),
('BFjjLjea-O', 'Brachiosaurus', 'BRAK-ee-oh-sore-us', 'arm lizard', 'herbivorous', 30, 'Late Jurassic', '155, 140', 'Brachiosaurus was a large, North American sauropod dinosaur with an arch encircling its nasal opening.', true),
('iOVNUcv-ww', 'Compsognathus', 'komp-sog-NATH-us', 'pretty jaw', 'carnivorous', 0.65, 'Late Jurassic', '145, 140', 'Compsognathus was small and bipedal, roughly the size of a turkey. It lived in Europe and was the first dinosaur genus to be portrayed with feathers.', true),
('WHQcpcOj0G', 'Dracorex', 'dray-ko-rex', 'dragon king', 'herbivorous', 4, 'Late Cretaceous', '66', 'Dracorex hogwartsia was a pachycephalosaur that did not have a domed head. Instead, its skull was adorned with spikes and frills reminiscent of a dragon. A skull was discovered in the Hell Creek Formation in South Dakota and donated to the Children''s Museum of Indianapolis in 2004. Its name was inspired by J.K. Rowling''s Harry Potter series and the young visitors to the children''s museum.', true),
('GKl035EYKN', 'Elasmosaurus', 'ee-LAZ-mo-sore-us', 'thin plate lizard', 'carnivorous', 14, 'Late Cretaceous', '80.5', 'Elasmosaurus was an aquatic dinosaur with an extremely long neck that likely fed on other smaller aquatic fauna like fish, molluscs, and squid. E.D. Cope mistakenly placed the skull of an Elasmosaurus on the much shorter tail rather than the extremely long neck.', true),
('V53DvdhV2A', 'Giraffatitan', 'ji-raf-e-tie-tan', 'giraffe titan', 'herbivorous', 23, 'Late Jurassic', '154, 142', 'Giraffatitan was a large sauropod related to Brachiosaurus with huge nostrils and nasal openings in its skull.', false),
('2GglUqKT0G', 'Indosuchus', 'in-doh-sook-us', 'Indian crocodile', 'carnivorous', 7, 'Late Cretaceous', '70, 66', 'Indosuchus had a flattened crest on its skull.', false),
('aIR95B2TWm', 'Jingshanosaurus', 'jing-shahn-oh-sore-us', 'Jingshan lizard', 'herbivorous', 5, 'Early Jurassic', '205, 190', 'Jingshanosaurus was one of the last prosauropods, a long-necked herbivore able to walk on two legs.', true),
('Pr6kc4Q_Xf', 'Khaan', 'kahn', 'ruler', 'omnivorous', 1.8, 'Late Cretaceous', '81, 75', 'Khaan was an oviraptor with a parrot-like beak, discovered in Mongolia.', true),
('GOycwH_EiU', 'Minmi', 'min-mie', 'Minmi Crossing, Queensland, Australia', 'herbivorous', 3, 'Early Cretaceous', '121, 112', 'Minmi was a small, anklyosaurian, armored dinosaur discovered in Australia.', false),
('Lfp-pAYmDv', 'Ouranosaurus', 'oo-RAH-noh-sore-us', 'brave monitor lizard', 'herbivorous', 7, 'Early Cretaceous', '125, 112', 'Ouranosaurus was an iguanodont dinosaur in Africa. It had a large sail on its back supported by long, wide neural spines and an elnogated, flat skull.', true),
('ft5Gs5izdq', 'Parasaurolophus', 'PARR-eh-saw-ROL-off-us / PARR-eh-sawr-eh-LOH-fus', 'near crested lizard', 'herbivorous', 11, 'Late Cretaceous', '76, 74', 'Found in Canada and the USA, Parasaurolophus was a hadrosaur most famous for its long, elaborate cranial crest.', true),
('JIj72eqrz6', 'Spinosaurus', 'SPINE-oh-SORE-us', 'spine lizard', 'carnivorous', 18, 'Early Cretaceous', '112, 97', 'Spinosaurus was one of the largest carnivorous dinosaurs to walk the Earth. Its diet consisted mostly of fish and the large spines on its back likely formed a sail.', true),
('wuL4ddBinQ', 'Tyrannosaurus', 'tie-RAN-oh-sore-us', 'tyrant lizard', 'carnivorous', 12, 'Late Cretaceous', '68, 66', 'Tyrannosaurus is well-represented in both fiction and history with over 50 specimens discovered. It and was one of the last non-avian dinosaurs to exist before the extinction event. Tyrannosaurus had a massive skull and a long heavy tail.', true),
('qk1bNQA9_n', 'Utahraptor', 'YOO-tah-RAP-tor', 'Utah predator', 'carnivorous', 6, 'Early Cretaceous', '112, 100', 'Found in the USA, Utahraptor resembled velociraptor but much larger, prompting Robert T. Bakker to pronounce it ''Spielberg''s raptor'' due to the velociraptors in the movie Jurassic Park being portrayed much larger than their historical counterparts.', true),
('sW_2EWCsDkE', 'Vulcanodon', 'vul-ka-oh-don', 'vulcano tooth', 'herbivorous', 6.5, 'Early Jurassic', '83, 175', 'Vulcanodon was a primitive sauropod that lived in southern Africa.', true),
('U9vuZmgKwUr', 'Xenoceratops', 'ZEE-no-SEH-ruh-tops', 'alien horned face', 'herbivorous', 6, 'Early Cretaceous', '78.5, 77.5', 'Xenoceratops had horns and a bony frill with elaborate ornamentation of projections, knobs, and spikes.', false),
('k-fVc9G-5Gm', 'Zephyrosaurus', 'ZEF-ear-ro-SORE-us', 'West wind lizard', 'herbivorous', 1.8, 'Early Cretaceous', '120, 110', 'An ornithopod dinosaur known only by a partial skull and postcranial fragments, not much about Zephyrosaurus has been discovered.', true);